language: csharp
solution: src/src.sln
install:
  - nuget restore src/src.sln
script:
  - xbuild /p:Configuration=Release src/src.sln
branches:
  only:
    - master
    - develop
notifications:
  email:
    on_success: never
    on_failure: never